### ISSUE TITLE
Enhance Conference UI

### ISSUE THREAD

**Issue by NathanVss** [numerique-gouv/meet#234]
## Feature Request

**Describe the solution you'd like**

Enhance the visio conference ui according to the following sketch

![Image](https://github.com/user-attachments/assets/1bf28060-77c7-44d2-b07c-4a4436504842)

## Todo

- [ ] Active button must use pressed state
- [ ] Pre join screen button
- [ ] Navbar control right

## Future

- [ ] Menu lists
- [ ] Settings
- [ ] Layout of webcams
- [ ] Notifs
- [ ] Members panel
- [ ] Chat
- [ ] Admin
- [ ] Control bar mobile
- [ ] Pre join
